project:
  type: website

website:
  navbar:
    title: "Pete Lawson"
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
      - href: "media/peter-lawson-cv.pdf"
        text: Curriculum Vitae
  page-footer:
    left: Copyright 2025, Pete Lawson
    right: This website was built in {{< fa brands r-project>}} with [Quarto](https://quarto.org) & deployed with [Netlify](https://www.netlify.com/)
      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true
    page-layout: full
    
execute:
  freeze: auto


