project:
  type: website

website:
  navbar:
    title: "Pete Lawson"
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer:
    left: Copyright 2024, Pete Lawson
    right: This website was built in [RStudio](https://posit.co/products/open-source/rstudio/) with [Quarto](quarto.org) and {{< fa heart title="a heart">}}  
      

format:
  html:
    theme: 
      - cosmo
      - styles.scss
    toc: true
    page-layout: full
    
execute:
  freeze: auto


