---
title: "About"
---

I am the Data and Visualization Librarian
 in [Data Services](https://dataservices.library.jhu.edu/){target="_blank"} at Johns Hopkins University. I love the statistical programming language R, cycling 🚲, and sprawling used bookstores with ornery owners.

I studied computational topology at Tulane, exploring the importance of cancer morphology in diagnosis and prognosis, finishing my Ph.D. in 2020. During my Ph.D. I cofounded an automated digital pathology company, [Instapath](https://www.instapathbio.com/){target="_blank"}. I developed educational materials and taught workshops for the Tulane Library, as well as becoming a certified Software Carpentries instructor, before moving into libraries full time. I am open to new projects and collaborations, and you can find me on [GitHub](https://github.com/pete-lawson){target="_blank"} or [LinkedIn](https://www.linkedin.com/in/lawson){target="_blank"}.

I live in DC with my wife and our dog Chewie - named for the New Orleans Mardi Gras walking parade [Chewbacchus](https://chewbacchus.org/){target="_blank"}.

This site was built in R using [Quarto](quarto.org){target="_blank"}, and deployed using Netlify. My blog posts are released under a [Creative Commons Attribution-ShareAlike 4.0 International License](https://creativecommons.org/licenses/by-sa/4.0/){target="_blank"}.
